# Generated by Django 4.0.1 on 2022-02-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posteo',
            options={'verbose_name': 'posteo', 'verbose_name_plural': 'posteos'},
        ),
        migrations.AlterField(
            model_name='posteo',
            name='contenido',
            field=models.TextField(),
        ),
    ]
