# Generated by Django 4.0.1 on 2022-02-09 18:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_posteo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='contenido',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
