# Generated by Django 4.0.1 on 2022-02-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_posteo_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='Pequeña descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
